$(document).ready(function(){
    $("#signup-form").validate({
       rules:{
        fname:{
            required:true,
            minlength:4
        },
        sname:{
            required:true,
            minlength:2
        },
        email:{
            required:true,
            email:true
        },
        password:{
            required:true,
            minlength:6
        },
        mobile:{
            required:true,
            digits:true,
            minlength:10
        },
        commentbox:{
            required:true,
            minlength:10,
        }
       } ,
       messages:{
        password:{
            minlength:"Must contain at least one number and one uppercase and lowercase letter, and at least 6 or more characters",
        },
        mobile:{
            minlength:"Must contain 10 digits", 
        }
       }
    })
})